---
version: 2.1
jobs:
  deploy:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    working_directory: ~/checkout
    steps:
      - checkout
      - run:
          name: check basic staff
          command: |
             pwd
             ls
      - run:
          name: Install ansible on puclic instance
          command: |
             ssh $SSH_USER@$SSH_HOST "hostname; sudo apt-get update; sudo apt install ansible -y"
      - run:
          name: Edit ansible vars
          command: |
             cd ansible
             echo "repo: << pipeline.parameters.repo >>" > vars.yml 
             echo "branch: << pipeline.parameters.branch >>" > vars.yml
             cat vars.yml
      - run:
          name: Send ansible directory to public instance (from checkout)
          command: |
             scp -r ./ansible "$SSH_USER@$SSH_HOST:/home/$SSH_USER"                    
      - run:
          name: Run ansible playbook
          command: |
             ssh $SSH_USER@$SSH_HOST "cd ansible; ansible-playbook playbook.yaml"

parameters:
  repo:
    default: latest
    type: string
  branch:
    default: latest
    type: string

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main # only deploy on the main branch
# ssh $SSH_USER@$SSH_HOST "ansible dev -m command -a 'hostname'"
# - run: ssh $SSH_USER@$SSH_HOST "ansible-playbook /home/ubuntu/ansible/playbook.yaml"
# - run: ssh $SSH_USER@$SSH_HOST "ansible dev -i /home/ubuntu/ansible/inventory -m file -a 'path=/home/ubuntu/ubuntu_test.txt state=touch'"
#- run: ssh $SSH_USER@$SSH_HOST "ansible all -i inventory -m ping"