---
- hosts: dev
  vars_files:
    - ~/ansible/vars.yml  
  tasks:
  - name: Install git
    apt:
      name: git
      state: present
  - name: Example clone of a single branch
    ansible.builtin.git:
      repo: "{{ repo }}"
      dest: /home/ubuntu/repos
      accept_hostkey: yes
      key_file: /home/ubuntu/.ssh/github
      version: "{{ branch }}"
# src - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
